
%% Fetch a lightweight dataset
clear
niak_gb_vars
niak_wget('data_test_niak_mnc1');

%% Setting input/output files

% All datasets are relative to current path
path_data = [pwd filesep];

% WARNING: Do not use underscores '_' in the IDs of subject, sessions or runs. This may cause bugs in subsequent pipelines.

% Subject 1
% Structural scan
files_in.subject1.anat                = [path_data 'data_test_niak_mnc1/anat_subject1.mnc.gz'];       
% fMRI run 1
files_in.subject1.fmri.session1.motor = [path_data 'data_test_niak_mnc1/func_motor_subject1.mnc.gz']; 

% Subject 2
% Structural scan
files_in.subject2.anat                = [path_data 'data_test_niak_mnc1/anat_subject2.mnc.gz'];       
% fMRI run 1
files_in.subject2.fmri.session1.motor = [path_data 'data_test_niak_mnc1/func_motor_subject2.mnc.gz']; 

%% Specify manually a template for the T1 and fMRI data
% If not specified, NIAK will use the MNI 2009 symmetric template by default
opt.template.t1           = [path_data 'data_test_niak_mnc1/mni_icbm152_asym_09a_5mm' filesep 'mni_icbm152_t1_tal_nlin_asym_09a_5mm.mnc.gz'];
opt.template.mask         = [path_data 'data_test_niak_mnc1/mni_icbm152_asym_09a_5mm' filesep 'mni_icbm152_t1_tal_nlin_asym_09a_mask_5mm.mnc.gz'];
opt.template.mask_eroded  = [path_data 'data_test_niak_mnc1/mni_icbm152_asym_09a_5mm' filesep 'mni_icbm152_t1_tal_nlin_asym_09a_mask_eroded5mm_5mm.mnc.gz'];
opt.template.mask_dilated = [path_data 'data_test_niak_mnc1/mni_icbm152_asym_09a_5mm' filesep 'mni_icbm152_t1_tal_nlin_asym_09a_mask_dilated5mm_5mm.mnc.gz'];
opt.template.mask_wm      = [path_data 'data_test_niak_mnc1/mni_icbm152_asym_09a_5mm' filesep 'mni_icbm152_t1_tal_nlin_asym_09a_mask_pure_wm_5mm.mnc.gz'];
opt.template.fmri         = [gb_niak_path_niak 'template' filesep 'roi_aal_3mm.mnc.gz'];                                                                           
opt.template.aal          = [gb_niak_path_niak 'template' filesep 'roi_aal_3mm.mnc.gz'];                                                                           
opt.template.mask_vent    = [gb_niak_path_niak 'template' filesep 'roi_ventricle.mnc.gz'];                                                                         
opt.template.mask_willis  = [gb_niak_path_niak 'template' filesep 'roi_stem.mnc.gz'];  

%% Pipeline options

%% General
% Where to store the results
opt.folder_out  = [path_data 'fmri_preprocess/'];    
% The amount of outputs that are generated by the pipeline. 
% 'all' will keep intermediate outputs
% 'quality_control' will only keep the quality control outputs. 
opt.size_output = 'quality_control';                             

%% Pipeline manager 
% See http://psom.simexp-lab.org/psom_configuration.html for more details on PSOM configuration
% Use up to four threads
opt.psom.max_queued = 4;       

%% Slice timing correction (niak_brick_slice_timing)
% Slice timing order 
% available options : 'sequential ascending', 
%                     'sequential descending' 
%                     'interleaved ascending'
%                     'interleaved descending')
opt.slice_timing.type_acquisition = 'interleaved ascending'; 
% Scanner manufacturer. Only the value 'Siemens' will actually have an impact
opt.slice_timing.type_scanner     = 'Bruker';                
% The delay in TR ("blank" time between two volumes)
opt.slice_timing.delay_in_tr      = 0;                       
% Number of dummy scans to suppress.
opt.slice_timing.suppress_vol     = 0;                       
% Apply a correction for non-uniformities on the EPI volumes (1: on, 0: of). 
% This is particularly important for 32-channels coil.
opt.slice_timing.flag_nu_correct  = 1;                       
% The distance between control points for non-uniformity correction 
% (in mm, lower values can capture faster varying slow spatial drifts).
opt.slice_timing.arg_nu_correct   = '-distance 200';         
% Set the origin of the volume at the center of mass of a brain mask. 
% This is useful only if the voxel-to-world transformation from the DICOM header 
% has somehow been damaged. This needs to be assessed on the raw images.
opt.slice_timing.flag_center      = 0;                       
% Skip the slice timing (0: don't skip, 1 : skip). 
% Note that only the slice timing corretion portion is skipped, 
% not all other effects such as FLAG_CENTER or FLAG_NU_CORRECT
opt.slice_timing.flag_skip        = 0;                       
 
%% Motion estimation (niak_pipeline_motion)
% The session that is used as a reference. 
% In general, use the session including the acqusition of the T1 scan.
opt.motion.session_ref  = 'session1'; 

%% resampling in stereotaxic space
% The voxel size to use in the stereotaxic space
% here 10 mm is used to generate small files
opt.resample_vol.voxel_size    = 10;

%% Linear and non-linear fit of the anatomical image in the stereotaxic
% space (niak_brick_t1_preprocess)
% Parameter for non-uniformity correction. 200 is a suggested value for 1.5T images, 75 for 3T images. 
% If you find that this stage did not work well, this parameter is usually critical to improve the results.
opt.t1_preprocess.nu_correct.arg = '-distance 75'; 

%% Temporal filtering (niak_brick_time_filter)
% Cut-off frequency for high-pass filtering, or removal of low frequencies (in Hz). 
% A cut-off of -Inf will result in no high-pass filtering.
opt.time_filter.hp = 0.01; 
% Cut-off frequency for low-pass filtering, or removal of high frequencies (in Hz). 
% A cut-off of Inf will result in no low-pass filtering.
opt.time_filter.lp = Inf;  

% Regression of confounds and scrubbing (niak_brick_regress_confounds)
% Turn on/off the regression of the average white matter signal (true: apply / false : don't apply)
opt.regress_confounds.flag_wm = true;            
% Turn on/off the regression of the average of the ventricles (true: apply / false : don't apply)
opt.regress_confounds.flag_vent = true;          
% Turn on/off the regression of the motion parameters (true: apply / false : don't apply)
opt.regress_confounds.flag_motion_params = true; 
% Turn on/off the regression of the PCA-based estimation of the global signal (true: apply / false : don't apply)
opt.regress_confounds.flag_gsc = false;          
% Turn on/off the scrubbing of time frames with excessive motion (true: apply / false : don't apply)
opt.regress_confounds.flag_scrubbing = true;     
% The threshold on frame displacement that is used to determine frames with excessive motion 
% in the scrubbing procedure
opt.regress_confounds.thre_fd = 0.5;             

%% Correction of physiological noise (niak_pipeline_corsica)
% Number of components estimated during the ICA. 20 is a minimal number, 
% 60 was used in the validation of CORSICA.
opt.corsica.sica.nb_comp             = 60;    
% This threshold has been calibrated on a validation database 
% as providing good sensitivity with excellent specificity.
opt.corsica.threshold                = 0.15;  
% Skip CORSICA (0: don't skip, 1 : skip). 
% Even if it is skipped, ICA results will be generated for quality-control purposes.
% The method is not currently considered to be stable enough for production unless it is manually supervised.
opt.corsica.flag_skip                = 1;     

%% Spatial smoothing (niak_brick_smooth_vol)
% Full-width at maximum (FWHM) of the Gaussian blurring kernel, in mm.
opt.smooth_vol.fwhm      = 6;  
% Skip spatial smoothing (0: don't skip, 1 : skip)
opt.smooth_vol.flag_skip = 0;  

%% Tune specific parameters on a subject-by-subject basis
% Anything that usually goes in opt can go in param. 
% These options are merged with what have been specified in opt
opt.tune(1).subject = 'subject1';
opt.tune(1).param.t1_preprocess.nu_correct.arg = '-distance 85'; 

opt.tune(2).subject = 'subject2';
opt.tune(2).param.t1_preprocess.nu_correct.arg = '-distance 55'; 

%% Run the fmri_preprocess pipeline 

[pipeline,opt] = niak_pipeline_fmri_preprocess(files_in,opt);